### ISSUE TITLE
Production build bug on webpack-assets-manifest

### ISSUE THREAD

**Issue by poomer1988** [packmule/packmule#15]
We have a problem on npm build:production with our SVG sprites.
They can`t be found because the path in the manifest.json is wrong

**Comment by thasmo** [comment]
`packmule` uses `external-svg-sprite-loader` for sprite generation and `webpack-assets-manifest` for the generation of the manifest and beyond that we do not configure anything special.

After talking to @poomer1988 it turned out that the actual problem was not the generated manifest in the first place but rather some minor issue with using the Symfony Asset component.
